name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    steps:
      # bevy_cli installs an older version of wasm-opt via https://crates.io/crates/wasm-opt which is
      # incompatible with the wasm produced by rust 1.87
      - uses: sigoden/install-binary@v1
        with:
          repo: WebAssembly/binaryen
          name: wasm-opt

      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install bevy_cli
        run: |
          cargo install --git https://github.com/TheBevyFlock/bevy_cli --tag cli-v0.1.0-alpha.1 --locked bevy_cli

      - name: Bundle
        run: |
          bevy build --yes --release --profile web-dist web --bundle

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./target/bevy_web/web-dist/kilter_brain
          retention-days: 1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
